### ISSUE TITLE
tb 11 question.

### ISSUE THREAD

**Issue by mahern** [pi3ch/tb2taskwarrior#1]
I can't find a way to add a custom button to TB 11. Is there a method I am missing or a workaround? Accelerator key, etc?

Thanks in advance.

**Comment by pi3ch** [comment]
Custom Button is compatible with TB 3.3-. unless you modify the installation file.

##

**Comment by treffynnon** [comment]
I installed the latest development build of custombuttons from http://custombuttons.mozdev.org/devbuilds.html and it worked just fine in TB latest.

**Comment by mahern** [comment]
Thank you very much. Works perfectly.
Great functionality now.
